environments:
  production:
  ci:

repositories:
- name: w3f
  url: https://w3f.github.io/helm-charts

releases:
- name: kusama-payouts-claimer
  chart: ../charts/polkadot-k8s-payouts
  namespace: kusama
  values:
  - ./config/claimer.yaml.gotmpl
  - ./config/kusama/claimer.yaml.gotmpl

- name: polkadot-payouts-claimer
  chart: ../charts/polkadot-k8s-payouts
  namespace: polkadot
  values:
  - ./config/claimer.yaml.gotmpl
  - ./config/polkadot/claimer.yaml.gotmpl  
