environments:
  production:
    values:
    - ../config/nodes.yaml
  local:
    values:
    - ../config/nodes.yaml

repositories:
- name: w3f
  url: https://w3f.github.io/helm-charts/

releases:
- name: kusama-payouts-claimer
  chart: ../charts/polkadot-k8s-payouts
  values:
  - ./config/claimer.yaml.gotmpl
  - ./config/kusama/claimer.yaml.gotmpl

- name: polkadot-payouts-claimer
  chart: ../charts/polkadot-k8s-payouts
  values:
  - ./config/claimer.yaml.gotmpl
  - ./config/polkadot/claimer.yaml.gotmpl  
