apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-wallet
type: Opaque
data:
  claimer_wallet_json: {{ .Values.secret.claimerWalletValue | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-password
type: Opaque
data:
  claimer_password: {{ .Values.secret.claimerPasswordValue | b64enc | quote }}  